Repository jawon22/SemiProject5, pull requests merged in 2023-10, with the labels that each got.

#74 오류페이지 구현 및 접근제한 구현중
  realSemiProject/src/main/java/com/semi/project/configuration/InterceptorConfiguration.java
  realSemiProject/src/main/java/com/semi/project/error/AuthorityException.java
  realSemiProject/src/main/java/com/semi/project/error/ExceptionControllerAdvice.java
  realSemiProject/src/main/java/com/semi/project/error/NoTargetException.java
  realSemiProject/src/main/java/com/semi/project/interceptor/AdminInterceptor.java
  realSemiProject/src/main/java/com/semi/project/interceptor/BoardDetailDeleteInterceptor.java
  realSemiProject/src/main/java/com/semi/project/interceptor/BoardOwnerInterceptor.java
  realSemiProject/src/main/java/com/semi/project/interceptor/MemberInterceptor.java
  realSemiProject/src/main/java/com/semi/project/interceptor/TripperLevelInterceptor.java
  realSemiProject/src/main/webapp/WEB-INF/views/error/500.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/error/authority.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/error/noTarget.jsp
Labels: enhancement

#77 home 수정
  realSemiProject/src/main/webapp/WEB-INF/views/home.jsp
Labels: duplicate

#78 일반회원일 경우 정보게시판 글쓰기 차단 인터셉터 구현
  realSemiProject/src/main/java/com/semi/project/error/ExceptionControllerAdvice.java
  realSemiProject/src/main/java/com/semi/project/interceptor/TripperLevelInterceptor.java
Labels: enhancement

#82 페이지 네비게이터 (현재페이지) 수정
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/vo/PaginationVO.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/board/reportList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/blockList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/freeList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/reviewList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/noticeList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/qnaList.jsp
Labels: bug

#84 비밀글 인터셉터 구현완료(관리자+작성자) 외 접근 차단
  realSemiProject/src/main/java/com/semi/project/configuration/InterceptorConfiguration.java
  realSemiProject/src/main/java/com/semi/project/interceptor/QnASecretInterceptor.java
Labels: enhancement

#87 댓글 표시 수정 및 회원가입 이메일 오류 수정
  realSemiProject/src/main/webapp/WEB-INF/views/board/communityAll.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/freeList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/reviewList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/join.jsp
Labels: bug

#93 게시판 목록 이미지아이콘 삭제
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/BoardListDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/BoardListMapper.java
  realSemiProject/src/main/java/com/semi/project/mapper/BoardTop10Mapper.java
  realSemiProject/src/main/webapp/WEB-INF/views/board/communityAll.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/freeList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/reviewList.jsp
Labels: bug

#94 메인페이지 썸네일 리스트 수정
  realSemiProject/src/main/java/com/semi/project/controller/HomeController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDao.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/MainPageListDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/MainPageListMapper.java
Labels: bug

#100 비밀글 인터셉터 수정
  realSemiProject/src/main/java/com/semi/project/configuration/InterceptorConfiguration.java
  realSemiProject/src/main/java/com/semi/project/interceptor/QnASecretInterceptor.java
  realSemiProject/src/main/java/com/semi/project/rest/MemberRestController.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/detail.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/edit.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/login.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/myLikeList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/myReplyList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/myWriteList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/mypage.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/footer.jsp
Labels: bug

#101 상세 검색 오류 수정
  realSemiProject/src/main/java/com/semi/project/configuration/InterceptorConfiguration.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: bug

#108 정보게시판 등급별 작성권한 인터셉터 수정완료
  realSemiProject/src/main/java/com/semi/project/interceptor/TripperLevelInterceptor.java
Labels: bug

#109 일괄삭제 기능 수정
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
Labels: bug

#112 회원 등급 관리 수정
  realSemiProject/src/main/java/com/semi/project/controller/MemberMypageController.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/service/RegularService.java
  realSemiProject/src/main/java/com/semi/project/service/RegularServiceImpl.java
  realSemiProject/src/main/resources/static/css/commons.css
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/edit.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/home.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/infoChange.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/login.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/mypage.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/pwChange.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/footer.jsp
Labels: duplicate

#128 Taeseok
  realSemiProject/src/main/webapp/WEB-INF/views/board/detail.jsp
Labels: bug

#135 배포전 수정 중
  realSemiProject/src/main/java/com/semi/project/controller/MemberMypageController.java
  realSemiProject/src/main/resources/application.properties
  realSemiProject/src/main/resources/static/images/favicon.ico
  realSemiProject/src/main/resources/static/images/favicon2.ico
  realSemiProject/src/main/resources/static/images/favicon3.ico
  realSemiProject/src/main/resources/static/images/favicon4.ico
  realSemiProject/src/main/resources/static/images/logofavicon.png
  realSemiProject/src/main/resources/static/images/logofavicon2.png
  realSemiProject/src/main/resources/static/images/logofavicon3.png
  realSemiProject/src/main/webapp/WEB-INF/views/board/all.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/communityAll.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/home.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/login.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/header.jsp
Labels: bug

#136 summernote 수정중
  realSemiProject/src/main/webapp/WEB-INF/views/board/detail.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/write.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/error/authority.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/error/noTarget.jsp
Labels: bug

#137 수정중
  realSemiProject/src/main/resources/static/images/logofavicon2.ico
  realSemiProject/src/main/resources/static/images/logofavicon2.png
  realSemiProject/src/main/resources/static/images/logofavicon5.ico
  realSemiProject/src/main/resources/static/images/logofavicon6.ico
  realSemiProject/src/main/webapp/WEB-INF/views/home.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/header.jsp
Labels: bug
