Repository jawon22/SemiProject5, pull requests merged in 2023-09, with the labels that each got.

#4 회원 Controller, member 폴더, join JSP 생성
  realSemiProject/src/main/java/com/semi/project/controller/MemberController.java
  realSemiProject/src/main/webapp/WEB-INF/views/member/join.jsp
Labels: documentation

#10 멤버 로그인, 탈퇴 구현, 마이페이지 구현 중
  realSemiProject/src/main/java/com/semi/project/controller/MemberMypageController.java
  realSemiProject/src/main/resources/static/css/commons.css
  realSemiProject/src/main/webapp/WEB-INF/views/member/exit.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/exitFinish.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/login.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: enhancement

#16 아이디 찾기 구현
  realSemiProject/src/main/java/com/semi/project/controller/MemberController.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/MemberDto.java
  realSemiProject/src/main/java/com/semi/project/rest/MemberRestController.java
  realSemiProject/src/main/webapp/WEB-INF/views/member/searchId.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/searchIdFinish.jsp
Labels: enhancement

#17 멤버 mypage 기능 추가 구현
  realSemiProject/src/main/java/com/semi/project/controller/MemberMypageController.java
  realSemiProject/src/main/java/com/semi/project/dao/AttachmentDao.java
  realSemiProject/src/main/java/com/semi/project/dao/AttachmentDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/AttachmentDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/AttachmentMapper.java
  realSemiProject/src/main/webapp/WEB-INF/views/member/infoChange.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/login.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/logout.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/myWriteList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/mypage.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/pwChange.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/pwChangeFinish.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/header.jsp
Labels: enhancement

#18 Hyo
  realSemiProject/pom.xml
  realSemiProject/src/main/java/com/semi/project/configuration/EmailConfiguration.java
  realSemiProject/src/main/java/com/semi/project/configuration/EmailProperties.java
  realSemiProject/src/main/java/com/semi/project/controller/MemberController.java
  realSemiProject/src/main/java/com/semi/project/dao/CertDao.java
  realSemiProject/src/main/java/com/semi/project/dao/CertDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dto/CertDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/CertMapper.java
  realSemiProject/src/main/java/com/semi/project/rest/CertRestController.java
  realSemiProject/src/main/resources/application.properties
Labels: enhancement

#20 비밀번호찾기 기능 내 임시 비밀번호 전송을 위한 임시 비밀번호 랜텀 추출 구문 작성
  realSemiProject/src/main/java/com/semi/project/component/CertCodeRandom.java
  realSemiProject/src/main/java/com/semi/project/rest/CertRestController.java
Labels: enhancement

#22 Jawon
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDao.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/vo/PaginationVO.java
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#28 나이별 회원 통계 구현 중
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/StatDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/StatMapper.java
  realSemiProject/src/main/java/com/semi/project/rest/MemberRestController.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/stat.jsp
Labels: enhancement

#33 관리자 멤버 상세보기 기능 구현 중
  realSemiProject/src/main/java/com/semi/project/controller/AdminController.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/detail.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: enhancement

#34 관리자 기능 - 회원 통계 구현
  realSemiProject/src/main/java/com/semi/project/controller/MemberController.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/rest/MemberRestController.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/stat.jsp
Labels: enhancement

#37 회원, 관리자 기능 구현 중
  realSemiProject/src/main/java/com/semi/project/controller/AdminController.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/resources/static/images/user.png
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/detail.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/edit.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/infoChange.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: enhancement

#39 Jawon
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDao.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/vo/PaginationVO.java
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#41 정보게시판 좋아요/조회수 구현중
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#43 차단 회원 리스트 구현
  realSemiProject/src/main/java/com/semi/project/controller/AdminController.java
  realSemiProject/src/main/java/com/semi/project/controller/MemberController.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/BlockListDto.java
  realSemiProject/src/main/java/com/semi/project/dto/MemberBlockDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/BlockListMapper.java
  realSemiProject/src/main/java/com/semi/project/mapper/MemberBlockMapper.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/blockList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/admin/stat.jsp
Labels: enhancement

#45 정보게시판 목록 최신순,조회수,좋아요 정렬 구현
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#46 ajax 아이디체크 기능, qnanotice 글쓰기 기능 구현 중
  realSemiProject/src/main/java/com/semi/project/controller/QnaNoticeController.java
  realSemiProject/src/main/java/com/semi/project/dao/QnaNoticeDao.java
  realSemiProject/src/main/java/com/semi/project/dao/QnaNoticeDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/QnaNoticeDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/QnaNoticeListMapper.java
  realSemiProject/src/main/java/com/semi/project/mapper/QnaNoticeMapper.java
  realSemiProject/src/main/java/com/semi/project/rest/MemberRestController.java
  realSemiProject/src/main/java/com/semi/project/service/RegularServiceImpl.java
  realSemiProject/src/main/resources/static/js/boardWrite.js
  realSemiProject/src/main/webapp/WEB-INF/views/member/infoChange.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/login.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/mypage.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/write.jsp
Labels: enhancement

#47 정보게시판 목록 기능 추가
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDao.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/BoardListDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/BoardListMapper.java
  realSemiProject/src/main/java/com/semi/project/vo/PaginationVO.java
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#48 Hyo
  realSemiProject/src/main/java/com/semi/project/controller/AdminController.java
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDao.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDao.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/BlockDetailDto.java
  realSemiProject/src/main/java/com/semi/project/dto/BoardReportDto.java
  realSemiProject/src/main/java/com/semi/project/dto/ReportDto.java
  realSemiProject/src/main/java/com/semi/project/dto/ReportListDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/BlockDetailMapper.java
  realSemiProject/src/main/java/com/semi/project/mapper/BoardReportMapper.java
  realSemiProject/src/main/java/com/semi/project/mapper/ReportListMapper.java
  realSemiProject/src/main/java/com/semi/project/mapper/ReportMapper.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/blockList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/admin/member/detail.jsp
Labels: enhancement

#49 qnanotice 글쓰기, 상세페이지 기능 구현 중
  realSemiProject/src/main/java/com/semi/project/controller/QnaNoticeController.java
  realSemiProject/src/main/java/com/semi/project/dao/QnaNoticeDao.java
  realSemiProject/src/main/java/com/semi/project/dao/QnaNoticeDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/QnaNoticeDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/QnaNoticeMapper.java
  realSemiProject/src/main/resources/application.properties
  realSemiProject/src/main/resources/static/js/boardWrite.js
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/detail.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/write.jsp
  realSemiProject/src/test/java/com/semi/project/LoggingTest01.java
Labels: enhancement

#53 신고 목록 내 체크박스 기능 구현 중
  realSemiProject/src/main/java/com/semi/project/controller/AdminController.java
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dao/MemberDaoImpl.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/board/reportList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#55 회원가입 프론트 구현 중
  realSemiProject/src/main/webapp/WEB-INF/views/member/join.jsp
Labels: enhancement

#56 Q&A 게시판 목록 구현 중
  realSemiProject/src/main/java/com/semi/project/controller/QnaNoticeController.java
  realSemiProject/src/main/java/com/semi/project/dao/QnaNoticeDao.java
  realSemiProject/src/main/java/com/semi/project/dao/QnaNoticeDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/dto/QnaNoticeDto.java
  realSemiProject/src/main/java/com/semi/project/mapper/QnaNoticeListMapper.java
  realSemiProject/src/main/java/com/semi/project/vo/PaginationVO.java
  realSemiProject/src/main/resources/static/images/notice.png
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/qnaNotice/noticeList.jsp
Labels: enhancement

#57 Jawon
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/resources/static/images/logo.png
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/home.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/footer.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/header.jsp
Labels: enhancement

#58 Jawon
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/resources/static/images/etc/cry.gif
  realSemiProject/src/main/resources/static/images/weather/spring.jpg
  realSemiProject/src/main/webapp/WEB-INF/views/board/all.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/template/header.jsp
Labels: enhancement

#60 Hyo
  realSemiProject/src/main/java/com/semi/project/controller/MemberController.java
  realSemiProject/src/main/java/com/semi/project/controller/MemberMypageController.java
  realSemiProject/src/main/java/com/semi/project/dao/CertDao.java
  realSemiProject/src/main/java/com/semi/project/dao/CertDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/rest/CertRestController.java
  realSemiProject/src/main/java/com/semi/project/rest/MemberRestController.java
  realSemiProject/src/main/resources/static/images/check-icon.png
  realSemiProject/src/main/resources/static/images/x-icon.png
  realSemiProject/src/main/webapp/WEB-INF/views/member/exitFinish.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/join.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/pwChangeFinish.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/searchPw.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/member/searchPwFinish.jsp
Labels: enhancement

#68 계절/지역 전체 페이지 구현(지도)
  realSemiProject/src/main/webapp/WEB-INF/views/board/all.jsp
Labels: enhancement

#72 신고현황 오류 수정
  realSemiProject/src/main/java/com/semi/project/controller/AdminController.java
  realSemiProject/src/main/java/com/semi/project/controller/BoardController.java
  realSemiProject/src/main/java/com/semi/project/dao/BoardDaoImpl.java
  realSemiProject/src/main/java/com/semi/project/rest/BoardRestController.java
  realSemiProject/src/main/webapp/WEB-INF/views/admin/board/reportList.jsp
  realSemiProject/src/main/webapp/WEB-INF/views/board/list.jsp
Labels: bug
